table Pedidos
	lineageTag: 4e9af4c4-9382-4235-b665-380b3aab6e26

	column 'ID Pedido'
		dataType: string
		lineageTag: 0d72fd97-282c-4940-adf8-605a695d9398
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Data Pedido'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 44993351-5c72-44ae-8710-4c70940bf064
		summarizeBy: none
		sourceColumn: Data Pedido

		variation Variation
			isDefault
			relationship: e74e29a5-1087-42d3-827e-45c759fed2f8
			defaultHierarchy: LocalDateTable_5cb12db3-5326-42c0-8250-29e77da48dca.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d2c1ab65-5704-47cc-a38a-64ab7e5e859d
		summarizeBy: none
		sourceColumn: Data Envio

		variation Variation
			isDefault
			relationship: 3f75b150-7bba-4f70-809d-34e010bf45ee
			defaultHierarchy: LocalDateTable_3ca7f115-3220-490c-96aa-7d714dbbd06c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Modo Envio'
		dataType: string
		lineageTag: adaa9ee8-74b9-4f69-bbdd-ad61e08c52c8
		summarizeBy: none
		sourceColumn: Modo Envio

		annotation SummarizationSetBy = Automatic

	column 'Prioridade Pedido'
		dataType: string
		lineageTag: 25678fee-ff84-4e3e-aa98-af153e97e022
		summarizeBy: none
		sourceColumn: Prioridade Pedido

		annotation SummarizationSetBy = Automatic

	partition Pedidos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\Power BI_Data Science\Curso Microsoft Power BI\Laboratório_2\1-datasets\Pedidos.csv"),[Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Pedido", type text}, {"Data Pedido", type date}, {"Data Envio", type date}, {"Modo Envio", type text}, {"Prioridade Pedido", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado")
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

